Create hash_map.h
Kcchernikov/HashMap pull request #1
Opened 2021-03-04 12:41 UTC by Kcchernikov

2021-06-20 21:07 UTC, glebshp requested changes

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +#include <cstddef>
пробел режет глаз

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +// Hash table with open addressing. Deleted items are marked dead and cleared when the table capacity is reallocated.
не сказано за счёт чего достигается линейное итерирование, ничего не сказано про масштабирование, нет ссылки на подробное описание алгоритма

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +class HashMap {
это главный класс в файле, так что надо либо его поместить первым вместе с комментарием над ним, либо в заголовке файла разместить описание, что же собственно перед нами (второй предпочтительнее)

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +  private:
приватные поля должны идти после всего остального, а не в самом начале класса

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +    Hash hasher;
у приватных полей такой же способ записи (стиль оформления имён) как у публичных методов, это не ок, можно, например, добавить в конец подчёркивание

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +    // Realocate memory with new capacity/
почему тут в конце комментария слеш, а не точка?

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +    std::pair<const KeyType, ValueType> *data = nullptr;
получается в коде смешаны низкоуровневое самостоятельное оперирование памятью и использование std::vector, что выглядит странно, почему мы не используем std::vector для data ?

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +    // Standard insert with open addressing, scanning from memory to the right for dead and occupied cells. Increasing the size by 10 times when the table is overloaded.
слишком длинный комментарий, строчка не влезает в экран

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +        while (occupied[id] != 0 && (occupied[id] == 2 || !(data[id].first == elem.first))) {
тут нужен комментарий, поясняющий что происходит в этом while

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +        if ((fullness + dead_elem) * 10 > capacity) {
все управляющие константы (10 и 100 в данном случае) нужно вынести в отдельные public константы, а не держать числами в коде

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +            change_capacity(std::max(static_cast<size_t>(8), fullness * 100));
100 это очень неэффективно

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +        while (occupied[id] != 0 && (occupied[id] == 2 || !(data[id].first == key))) {
вот этот код поиска общий с insert (и, наверняка, find), надо сделать одним методом, без копирования кода

2021-06-20 21:07 UTC, glebshp commented on hash_map.h
> +        auto beg2 = beg;
beg2 - странное название переменной

2021-06-21 15:01 UTC, Kcchernikov commented on hash_map.h
> +    std::pair<const KeyType, ValueType> *data = nullptr;
Видимо хотелось уменьшить время работы и место в памяти, в векторе хранится куда меньше данных чем в сырой памяти

2021-06-23 22:01 UTC, glebshp requested changes

2021-06-23 22:01 UTC, glebshp commented on hash_map.h
> +// This is a hash table class with open addressing based on linear probing. Deleted items are marked dead and cleared when the table capacity is reallocated.
очень длинная строка, не влезает в экран

2021-06-23 22:01 UTC, glebshp commented on hash_map.h
> +class Literator: public std::iterator<std::forward_iterator_tag, std::pair<KeyType, ValueType>> {
А что означает название Literator?

2021-06-23 22:01 UTC, glebshp commented on hash_map.h
> +        if ((fullness_ + dead_elem_) * SIZELIMIT > capacity_) {
Проверка условий на то что нужно сделать масштабирование тоже должна быть отдельным методом

2021-06-23 22:01 UTC, glebshp commented on hash_map.h
> +    HashMap(const Iterator& beg, const Iterator& en, const Hash& _hasher_ = Hash()): fullness_(0), dead_elem_(0), hasher_(_hasher_) {
beg и en такие себе названия, почему не start и finish?

2021-06-23 22:01 UTC, glebshp commented on hash_map.h
> +        Iterator begin1 = beg;
begin1 и begin2 тоже не информативные названия

2021-06-23 22:01 UTC, glebshp commented on hash_map.h
> +    std::pair<const KeyType, ValueType> *data_ = nullptr;
приходи в личку вот это обсуждать, я не понимаю зачем тебе два массива с низкоуровневым выделением памяти, а дальше вектор списков

2021-06-25 19:22 UTC, glebshp requested changes

2021-06-25 19:22 UTC, glebshp commented on hash_map.h
> +        if (occupied_[id] != 1) return temp;
скобки

2021-06-25 19:22 UTC, glebshp commented on hash_map.h
> +    constexpr static int SIZELIMIT = 4, INCREASE = 8, MINSIZE = 8, ALIVE = 1, DEAD = 2, EMPTY = 0;
сделай отдельно по строке на каждую константу

2021-06-25 19:22 UTC, glebshp commented on hash_map.h
> +    constexpr static int SIZELIMIT = 4, INCREASE = 8, MINSIZE = 8, ALIVE = 1, DEAD = 2, EMPTY = 0;
и поясни что они значат

2021-06-25 19:22 UTC, glebshp commented on hash_map.h
> +    // Deleting an item by marking it dead.
Из-за комментариев методы сливаются, добавь пустые строки между концом метода и началом комментария к следующему

2021-06-25 19:50 UTC, glebshp approved these changes

2021-06-25 19:54 UTC, merged